server {
    listen 80;
    server_name localhost;

    # 1. Frontend: AngularJS (Archivos estáticos)
    location / {
        root /var/www/frontend;
        index index.html;
        # Si no encuentra el archivo, le devuelve el index.html a Angular para que maneje el ruteo interno
        try_files $uri $uri/ /index.html;
    }

    # 2. Backend: API de Laravel
    location /api {
        alias /var/www/backend/public;
        try_files $uri $uri/ @laravel;
    }

    location @laravel {
        rewrite /api/(.*)$ /api/index.php?/$1 last;
    }

    # 3. Conexión con PHP-FPM (El contenedor 'app')
    location ~ \.php$ {
        root /var/www/backend/public;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}