server {
    listen 80;
    server_name localhost;

    # 1. Frontend: AngularJS (Archivos estáticos)
    location / {
        root /var/www/frontend;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. Backend: Laravel API (Directo al motor PHP, sin escalas)
    location /api {
        fastcgi_pass app:9000;
        include fastcgi_params;
        # Le clavamos el puntero directo al archivo principal de Laravel
        fastcgi_param SCRIPT_FILENAME /var/www/backend/public/index.php;
        # Nginx le va a pasar el REQUEST_URI original (/api/login) sin tocarlo
    }
}